server {
    listen 80;
    server_name ostogai.ru www.ostogai.ru;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name ostogai.ru www.ostogai.ru;
    ssl_certificate /etc/letsencrypt/live/ostogai.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ostogai.ru/privkey.pem;
    client_max_body_size 25M;
    location /koldunya/ {
        proxy_pass http://localhost:3001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location / {
        proxy_pass http://localhost:3080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_set_header Accept-Encoding "";
        sub_filter '</body>' '<script src="/delete-agent.js"></script><script src="/notice.js"></script><script src="/scroll-bottom.js"></script></body>';
        sub_filter_once on;
    }

    location ~ ^/(delete-agent|notice|scroll-bottom).js$ {
        root /var/www/html;
        add_header Content-Type application/javascript;
    }
}
server {
    listen 80;
    server_name koldunya.ostogai.ru;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name koldunya.ostogai.ru;
    ssl_certificate /etc/letsencrypt/live/koldunya.ostogai.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/koldunya.ostogai.ru/privkey.pem;
    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
